### ISSUE TITLE
Getting maintainer permission

### ISSUE THREAD

**Issue by guyluz11** [terrabythia/dart_chromecast#63]
Hello @terrabythia 

I would like to keep this package alive and getting permission to accept pr and upload a new version of the package.

As you can see by the open pr there are people that would like to contribute to this package and it will be a shame for them to do the same work over and over again in their separate forks.

Would love to help and continue to this awesome package.

In case you prefer not to touch the package another option is to upload a copy of the package from my fork but original package is preferred.

Thanks and waiting for your response

**Comment by guyluz11** [comment]
If anybody is looking for an alternative, you can use my fork of another cast package.
My fork makes it Dart native compatible

```
 cast: 
    git: 
      url: "https://github.com/guyluz11/flutter_cast.git"
      ref: "multicast_version"

```
